title: Josue A. Solares # your name (or website title) here
logo: /images/20201212_160802.jpg?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full-Stack Developer in Training 
  <br><br>
  Looking for Internship 
  <br><br>
  <br><br>
  Working Mastery of: HTML5, CSS3, P5.js, SQL, Javascript, Python and C#
  <br><br>
  Check out my <a href="https://mr-clean-code.github.io/Josue-Solares-Project-1/">Project Page</a>
  <br><br>
  <a href="https://www.linkedin.com/in/josue-solares">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
