title: Josue A. Solares # your name (or website title) here
logo: "20201212_160802.jpg" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full-Stack Developer in Training 
  <br><br>
  Looking for Internship 
  <br><br>
  <a href="www.linkedin.com/in/josue-solares
">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
